// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "swapi-poke-fusion",
    "version": "1"
  },
  "paths": {
    "/merge": {
      "get": {
        "summary": "mergeData",
        "description": "",
        "operationId": "mergeData.get./merge",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/store": {
      "post": {
        "summary": "storeData",
        "description": "",
        "operationId": "storeData.post./store",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/history": {
      "get": {
        "summary": "getHistory",
        "description": "",
        "operationId": "getHistory.get./history",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};