# .github/workflows/deploy-dev.yml
name: CI / Deploy Dev

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests only
        run: npm test -- --testPathIgnorePatterns="src/__tests__/integration"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            us-east-1

      - name: Prepare SSM parameters (Cognito)
        run: |
          aws ssm put-parameter --region us-east-1 \
            --name /fusion/dev/user_pool_id --type String --overwrite \
            --value "${{ secrets.COGNITO_POOL_ID }}"
          aws ssm put-parameter --region us-east-1 \
            --name /fusion/dev/user_pool_client_id --type String --overwrite \
            --value "${{ secrets.COGNITO_CLIENT_ID }}"

      - name: Deploy to AWS (stage dev)
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: npx serverless deploy --stage dev
